services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    links:
      - "caddy:caddy.localhost"


  caddy:
    image: caddy:2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro