services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    links:
      - "caddy-1:1.localhost"


  caddy-1:
    image: caddy:2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro